---
host:
  description: "IP address of the Morpheus (e.g.: 'fqdn.to.device' or '10.10.10.10')"
  type: "string"
  secret: false
  required: true
username:
  description: "Username for Morpheus"
  type: "string"
  required: true
password:
  description: "Password for Morpheus"
  type: "string"
  secret: true
  required: true
dbuser:
  description: "Username for user database"
  type: "string"
  secret: false
  required: false
dbpass:
  description: "Password for user database"
  type: "string"
  secret: true
  required: false
